**Actividad 4 (Evaluación) (Valores Atípicos)**

In [24]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [25]:
data = pd.read_excel('Gastos_y_costos_20_23.xlsx')
data.head()

,FECHA,FOLIO,UUID,RFC,PROVEEDOR,TIPO GASTO,GASTO,DESCRIPCION,TC,IMPORTE,IVA,RET ISR,RET IVA,TOTAL MX,TOTAL SAT,TIPO,STATUS,POLIZA,Columna1
0,2020-01-01,39408,BD20F436-72CC-4BE2-AD37-5999D71AA391,ARE080115PBA,ARSI RENTA SA DE CV,MAQUINARIA,NaN,"Descripción: REVOLVEDORA, Modelo: ULTRAMP9A, M...",1.0,0.00,2248.28,0.0,0.0,2248.28,16300.00,I,Vigente,NaN,14051.72
1,2020-01-01,0001010100750847116902,85AEAC2E-6395-44A0-9CB9-754D06893375,BNM840515VB1,"BANCO NACIONAL DE MEXICO, S.A.",COMISION BANCARIA,NaN,COMISION COBRADA,1.0,490.00,78.40,0.0,0.0,568.40,568.40,I,Vigente,NaN,0.00
2,2020-01-01,0001010100752163714102,BD0DFE85-D776-41CB-9C5C-4FA7923E687A,BNM840515VB1,"BANCO NACIONAL DE MEXICO, S.A.",COMISION BANCARIA,NaN,COMISION COBRADA,1.0,195.00,31.20,0.0,0.0,226.20,226.20,I,Vigente,NaN,0.00
3,2020-01-01,3663,EF4504D6-830D-415C-AF03-80CF54C5E28E,PSS120625C86,PROMOTORA DE SERVICIOS Y SOLUCIONES EMPRESARIA...,HONORARIOS CONTABLES,NaN,HONORARIOS CONTABLES\nDEL MES DE ENERO DEL 2020.,1.0,10694.25,1711.08,0.0,0.0,12405.33,12405.33,I,Vigente,NaN,0.00
4,2020-01-01,2849,EC2F4AA4-BA64-4E2E-A5B7-4EBBE042D6D3,ENA7006081P0,ELECTROTERMICA NACIONAL SA DE CV,COMPRAS,NaN,Pago,1.0,0.00,NaN,0.0,0.0,0.00,0.00,P,Vigente,NaN,0.00

**Paso 1 - Verificación de datos nulos.**  
En este proceso obtenemos una visualización sobre la ausencia de datos en las variables del data frame.

In [42]:
valores_nulos=data.isnull().sum()
valores_nulos

FECHA             0
FOLIO           189
UUID              0
RFC               0
PROVEEDOR         0
TIPO GASTO        0
GASTO          2502
DESCRIPCION       0
TC              391
IMPORTE          34
IVA             268
RET ISR           0
RET IVA           0
TOTAL MX          0
TOTAL SAT         0
TIPO              1
STATUS            0
POLIZA         3321
Columna1          0
dtype: int64

Dado que separaremos el data frame en 2 (datos categóricos y numéricos) se optó por utilizar el mismo tratamiento en datos nulos el cual será bfill.

In [43]:
data1 =data.fillna(method="bfill") 
data1

,FECHA,FOLIO,UUID,RFC,PROVEEDOR,TIPO GASTO,GASTO,DESCRIPCION,TC,IMPORTE,IVA,RET ISR,RET IVA,TOTAL MX,TOTAL SAT,TIPO,STATUS,POLIZA,Columna1
0,2020-01-01,39408,BD20F436-72CC-4BE2-AD37-5999D71AA391,ARE080115PBA,ARSI RENTA SA DE CV,MAQUINARIA,COMPRA,"Descripción: REVOLVEDORA, Modelo: ULTRAMP9A, M...",1.0,0.00,2248.28,0.0,0.0,2248.28,16300.00,I,Vigente,PE07-ENE20,14051.72
1,2020-01-01,0001010100750847116902,85AEAC2E-6395-44A0-9CB9-754D06893375,BNM840515VB1,"BANCO NACIONAL DE MEXICO, S.A.",COMISION BANCARIA,COMPRA,COMISION COBRADA,1.0,490.00,78.40,0.0,0.0,568.40,568.40,I,Vigente,PE07-ENE20,0.00
2,2020-01-01,0001010100752163714102,BD0DFE85-D776-41CB-9C5C-4FA7923E687A,BNM840515VB1,"BANCO NACIONAL DE MEXICO, S.A.",COMISION BANCARIA,COMPRA,COMISION COBRADA,1.0,195.00,31.20,0.0,0.0,226.20,226.20,I,Vigente,PE07-ENE20,0.00
3,2020-01-01,3663,EF4504D6-830D-415C-AF03-80CF54C5E28E,PSS120625C86,PROMOTORA DE SERVICIOS Y SOLUCIONES EMPRESARIA...,HONORARIOS CONTABLES,COMPRA,HONORARIOS CONTABLES\nDEL MES DE ENERO DEL 2020.,1.0,10694.25,1711.08,0.0,0.0,12405.33,12405.33,I,Vigente,PE07-ENE20,0.00
4,2020-01-01,2849,EC2F4AA4-BA64-4E2E-A5B7-4EBBE042D6D3,ENA7006081P0,ELECTROTERMICA NACIONAL SA DE CV,COMPRAS,COMPRA,Pago,1.0,0.00,5131.03,0.0,0.0,0.00,0.00,P,Vigente,PE07-ENE20,0.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3337,2020-12-01,125834,80BCB1D8-673F-495B-9C2A-4AC9F9CB38E5,SQS110113MU0,SERVICIO QUINTANA SUR S.A DE C.V,COMBUSTIBLE,G VTA,32011 MAGNA,1.0,129.79,20.21,0.0,0.0,150.00,150.00,I,Vigente,NaN,0.00
3338,2020-12-01,37652,D4C7C1FB-03A7-4046-A2BD-03EBE7DA861E,PSQ790724C90,"CIA. PERIODISTICA DEL SOL DE QUERETARO, S.A. D...",PUBLICIDAD,G VTA,82101504-PUBLICIDAD EN PERIODICOSCALOR Y CONTROL,1.0,2284.80,365.57,0.0,0.0,2650.37,2650.37,I,Vigente,NaN,0.00
3339,2020-12-01,160,FFCEE7D4-1F38-4D44-BE02-EB042DAACEE7,SQX981027RY5,"SUPER Q, S. A. DE C. V.",ALIMENTOS,G VTA,REF VICTORIA GROSELLA 3 LT PET NR,1.0,163.79,26.21,0.0,0.0,190.00,190.00,I,Vigente,NaN,0.00
3340,2020-12-01,634875,8DFF4F01-2F8B-4085-B116-05A314108B02,BIN940223KE0,"BANCO INVEX, S.A., INSTITUCION DE BANCA MULTIP...",COMISION BANCARIA,G FINA,COMISIONES E INTERESES,1.0,0.00,0.00,0.0,0.0,0.00,0.00,I,Vigente,NaN,0.00
3341,2020-12-01,1044477,F18225D6-4024-4F03-A15A-D18917386D59,EFE8908015L3,EFECTIVALE S. de R.L. de C.V.,COMBUSTIBLE,G VTA,CONSUMOS DE COMBUSTIBLE DE MONEDEROS ELECTRONICOS,1.0,14889.29,0.00,0.0,0.0,14889.29,14889.29,I,Vigente,NaN,0.00

In [29]:
valores_nulos=data1.isnull().sum()
valores_nulos

FECHA             0
FOLIO             0
UUID              0
RFC               0
PROVEEDOR         0
TIPO GASTO        0
GASTO             0
DESCRIPCION       0
TC                0
IMPORTE           0
IVA               0
RET ISR           0
RET IVA           0
TOTAL MX          0
TOTAL SAT         0
TIPO              0
STATUS            0
POLIZA         2898
Columna1          0
dtype: int64

Nos perctamaos que los campos se completan de manera adecuada

**Paso 2 - Identificación de outliers .**

Nos percatamos que en total contamos con un total de 8 variables numéricas, por lo cual pasaremos a realizar una extracción de estas con la finalidad de aplicar un filtro de detección de outliers.

In [44]:
data_num=data1.iloc[ : , [8,9,10,11,12,13,14,18]]  #Columnas no consecutivas
data_num.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3342 entries, 0 to 3341
Data columns (total 8 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   TC         3342 non-null   float64
 1   IMPORTE    3342 non-null   float64
 2   IVA        3342 non-null   float64
 3   RET ISR    3342 non-null   float64
 4   RET IVA    3342 non-null   float64
 5   TOTAL MX   3342 non-null   float64
 6   TOTAL SAT  3342 non-null   float64
 7   Columna1   3342 non-null   float64
dtypes: float64(8)
memory usage: 209.0 KB

**Procedimiento de detección de outliers mediante el método de cuartiles**

Establecemos los rangos intercuartílicos.

In [48]:
y=data_num

percentile25=y.quantile(0.25) #Q1
percentile75=y.quantile(0.75) #Q3
iqr= percentile75 - percentile25

Limite_Superior_iqr= percentile75 + 1.5*iqr
Limite_Inferior_iqr= percentile25 - 1.5*iqr
print("Limite superior permitido", Limite_Superior_iqr)
print("Limite inferior permitido", Limite_Inferior_iqr)

Limite superior permitido TC              1.00000
IMPORTE      6976.21375
IVA          1170.77250
RET ISR         0.00000
RET IVA         0.00000
TOTAL MX     7983.17750
TOTAL SAT    8269.28375
Columna1        0.00000
dtype: float64
Limite inferior permitido TC              1.00000
IMPORTE     -4160.35625
IVA          -687.92750
RET ISR         0.00000
RET IVA         0.00000
TOTAL MX    -4783.14250
TOTAL SAT   -4832.96625
Columna1        0.00000
dtype: float64

Vizualisamos los valores atípicos.

In [49]:
data3_iqr= data_num[(y<=Limite_Superior_iqr)&(y>=Limite_Inferior_iqr)]
data3_iqr

       TC  IMPORTE     IVA  RET ISR  RET IVA  TOTAL MX  TOTAL SAT  Columna1
0     1.0     0.00     NaN      0.0      0.0   2248.28        NaN       NaN
1     1.0   490.00   78.40      0.0      0.0    568.40     568.40       0.0
2     1.0   195.00   31.20      0.0      0.0    226.20     226.20       0.0
3     1.0      NaN     NaN      0.0      0.0       NaN        NaN       0.0
4     1.0     0.00     NaN      0.0      0.0      0.00       0.00       0.0
...   ...      ...     ...      ...      ...       ...        ...       ...
3337  1.0   129.79   20.21      0.0      0.0    150.00     150.00       0.0
3338  1.0  2284.80  365.57      0.0      0.0   2650.37    2650.37       0.0
3339  1.0   163.79   26.21      0.0      0.0    190.00     190.00       0.0
3340  1.0     0.00    0.00      0.0      0.0      0.00       0.00       0.0
3341  1.0      NaN    0.00      0.0      0.0       NaN        NaN       0.0

[3342 rows x 8 columns]

In [50]:
valores_nulos=data3_iqr.isnull().sum()
valores_nulos

TC             9
IMPORTE      424
IVA          411
RET ISR       45
RET IVA      253
TOTAL MX     420
TOTAL SAT    426
Columna1     240
dtype: int64

Procedemos a realizar una copia del dataframe con los intervalos cuartílicos y sustituimos los Na con el promedio de la variable analizada.

In [51]:
data4_iqr=data3_iqr.copy()
data4_iqr=data4_iqr.fillna(round(data3_iqr.mean(),1))
data4_iqr

       TC  IMPORTE     IVA  RET ISR  RET IVA  TOTAL MX  TOTAL SAT  Columna1
0     1.0     0.00  187.40      0.0      0.0   2248.28    1333.00       0.0
1     1.0   490.00   78.40      0.0      0.0    568.40     568.40       0.0
2     1.0   195.00   31.20      0.0      0.0    226.20     226.20       0.0
3     1.0  1093.80  187.40      0.0      0.0   1239.10    1333.00       0.0
4     1.0     0.00  187.40      0.0      0.0      0.00       0.00       0.0
...   ...      ...     ...      ...      ...       ...        ...       ...
3337  1.0   129.79   20.21      0.0      0.0    150.00     150.00       0.0
3338  1.0  2284.80  365.57      0.0      0.0   2650.37    2650.37       0.0
3339  1.0   163.79   26.21      0.0      0.0    190.00     190.00       0.0
3340  1.0     0.00    0.00      0.0      0.0      0.00       0.00       0.0
3341  1.0  1093.80    0.00      0.0      0.0   1239.10    1333.00       0.0

[3342 rows x 8 columns]

Verificamos que nuestro DF no cuente con datos nulos.

In [52]:
valores_nulos=data4_iqr.isnull().sum()
valores_nulos

TC           0
IMPORTE      0
IVA          0
RET ISR      0
RET IVA      0
TOTAL MX     0
TOTAL SAT    0
Columna1     0
dtype: int64

Finalmente unimos los DF de datos categóricos y numéricos.

In [53]:
df_limpio = pd.concat([data4_iqr, data1], axis=1)
df_limpio.isnull().sum()

TC                0
IMPORTE           0
IVA               0
RET ISR           0
RET IVA           0
TOTAL MX          0
TOTAL SAT         0
Columna1          0
FECHA             0
FOLIO             0
UUID              0
RFC               0
PROVEEDOR         0
TIPO GASTO        0
GASTO             0
DESCRIPCION       0
TC                0
IMPORTE           0
IVA               0
RET ISR           0
RET IVA           0
TOTAL MX          0
TOTAL SAT         0
TIPO              0
STATUS            0
POLIZA         2898
Columna1          0
dtype: int64

Guardamos los valores limpios para un posterior análisis.

In [41]:
df_limpio.to_csv("Datos_limpios.csv")